### PR TITLE
release candidate 2 - final

### PR DESCRIPTION
**Pull request by rananna**
@casainho , minor code cleanup and incorporate latest @4var1 changes.
no more changes expected - hope testing goes well tomorrow

### CODE REVIEW

**Comment by 4var1** [comment]
@rananna - you got that I put replacements in for led_alert and the combo with clear_queue yea? I know i said you could uncomment if you really wanted to - but I really hoped you'd search/replace and use the new equivalents :)

void led_sequence_play(uint8_t ui8_sequence);   - replaces led_alert(yada)  
void led_sequence_play_next(uint8_t ui8_sequence);    - replaces led_clear_queue() & led_alert(yada)

If you don't want to do it for this release - can you do it for the next please - so I can remove all the old calls from the header - and we all use the same code for queuing alerts?

I've been wanting to make the change all week - but I've been trying to make my led code more efficient :)

**Comment by rananna** [comment]
Yup, I saw that, but didn't have time to check it out for this release. So I kept everything the same for now as it is working well.
I will make the changes and incorporate in the next release.

**Comment by 4var1** [comment]
Ok cool thanks

**Comment by rananna** [comment]
I still need a function to stop a currently playing queue immediately.(for example when brakes are released.) I was using led_clear_queue(). Do you want me to use some other function?
pehaps led_sequence_cancel_play_until()?

**Pull request merged**
