### PR TITLE
Wired Remote Schematic v0.1

### PR DESCRIPTION
**Pull request by 4var1**

### CODE REVIEW

**Comment by rananna** [comment]
@4var1 , I have changed the wireless remote to use the new signalling functions.
However there is an issue.
When I tried to replace led_clear_queue () (used to stop a currently playing sequence) with led_clear_queue_and_stop_current_sequence(), the led remains lit instead of turning off.

**Comment by 4var1** [comment]
> @4var1 , I have changed the wireless remote to use the new signalling functions.
> However there is an issue.
> When I tried to replace led_clear_queue () (used to stop a currently playing sequence) with led_clear_queue_and_stop_current_sequence(), the led remains lit instead of turning off.

Hi - thanks for updating - but am a bit confused as that isn't one of the new calls exposed in the header? I'm off out now - will be back a bit later but try using the ones in the header only.

**Comment by rananna** [comment]
but which one? led_clear_queue works fine, but you didn't want me to use it.
What should I replace it with?

**Comment by 4var1** [comment]
The ones in the header - just under the old ones - and above the ones you put back. You don't need to call the queue mgmt directly - use the specific calls - like play_sequence_next (replaces clear queue/led_alert) - the comments tell you what's what...

**Comment by rananna** [comment]
I did that, please see first comment.

**Comment by 4var1** [comment]
In your first comment you reference a call that isn't defined in the header, no?

**Pull request merged**
