### PR TITLE
Led signalling works well

### PR DESCRIPTION
**Pull request by rananna**
@casainho ,
I have incorporated the latest changes from @4var1  and tested all modes of operation for the wireless remote
It works well, and I have updated the docs.(see PR there)
Notes:
1. the count for SOC was wrong  -fixed.
2. Added ability to set intensity level through double click (see docs)
3. added ability to enter hibernate mode through double click (see docs)

Please give it a try on your bike, and if it tests out well we could issue a new release.

### CODE REVIEW

**Comment by casainho** [comment]
Why do you keep updating the documentation on this repo as also on the main site http://opensourceebike.github.io/ ?

**Comment by rananna** [comment]
I thought you wanted to have the more detailed developer docs in the code repo, and the simplified docs in the docs repo. I have instructions on how to use in both locations.

**Comment by casainho** [comment]
So if I understand correctly, the how to use instructions are duplicated - and as user, everyone should look at only one place. So please save your time and do not do it next time :-)

Also on the https://opensourceebike.github.io/ you are keeping adding the BACK fixed link at the end of the page. That is also a bad practice as you can not guarantee that will return to correct previous page as that page it self can be linked from different places - that is why there is the internet browser back button as also Android back button. So save your time and do not add the BACK at the end of the page.

**Comment by rananna** [comment]
I was unsure how it works on Apple devices, so I added the back button.
Will remove.

**Pull request merged**
